### ISSUE TITLE
Enhancement request: allow modification of transparency

### ISSUE THREAD

**Issue by evilrix** [chingucoding/IndentRainbow#5]
I love the plugin (it really is great); however, when using a dark theme (to be honest, I've not tried a light theme) it's too in-your-face. A good solution would be to add a transparency level (as a percent) in the settings. If you look at the vscode [version](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow), you'll see that it is more transparent than this and so less of a distraction).

Also, having a quick way to enable/disable the rainbow effect would be useful (hot-key, or right-click context menu). This could be an alternative to adding transparency, but having both would really help improve this great plugin.

Thank you for your time and effort in making this plugin.

**Comment by chingucoding** [comment]
Technically you can edit the transparency since the colors are specified/can be specified as ARGB values.
However I understand that it would be easier to have a "global" option for that. I will try to implement that as soon I have time.

Regarding the hotkey, this may be nice to have and I'll look into it but this won't be a priority right now since there are more basic features missing.

**Comment by chingucoding** [comment]
Update: A "global" opacity multiplier has been added with version 0.2.5 of the extension to make it easier to increase/decrease opacity of all colors !

**Comment by chingucoding** [comment]
> Also, having a quick way to enable/disable the rainbow effect would be useful (hot-key, or right-click context menu). This could be an alternative to adding transparency, but having both would really help improve this great plugin.

I have looked further into this and as it seems, there is no "quick" way to change this, since disabling this would need you to reopen the document.I think 
this would kind of defeat the point of having a hotkey or menu item for that kind of action.
@evilrix Would you still want to have that kind of feature or is it ok to close this now since the feature would not seem feasible from user point of perspective?

**Comment by chingucoding** [comment]
Closing this as there seems to be no benefit and interest in this feature.
